# Generated by Django 3.2.8 on 2022-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Cinemas', 'verbose_name_plural': 'Cinemas'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movies', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='beginning_of_movie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ending_of_movie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
